CREATE DATABASE IF NOT EXISTS catatan_tugas_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE catatan_tugas_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  api_token VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tugas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  mata_kuliah VARCHAR(100) NOT NULL,
  judul VARCHAR(150) NOT NULL,
  deskripsi TEXT NULL,
  deadline DATE NOT NULL,
  status ENUM('belum', 'proses', 'selesai') NOT NULL DEFAULT 'belum',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tugas_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
